#!/usr/bin/env bash
# Installs and setup haproxy
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 273938-web-01 100.25.37.207:80 check
        server 273938-web-02 34.224.3.174:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
