#!/usr/bin/env bash
# Configures a ufw firewall to unblock only selected ports

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
